import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const email = process.env.E2E_REUSE_SYNTHETIC_EMAIL;
test('real self-report persists independently and reaches reading activities and PDF', async ({ page }, info) => {
  test.skip(process.env.E2E_REAL_FLOW !== 'true' || process.env.E2E_ALLOW_PAID_AI !== 'true' || !email, 'Requires approved local synthetic account and bounded provider use');
  test.setTimeout(240_000);
  expect(email).toMatch(/^umbra-e2e-\d+@test\.local$/);
  expect(['localhost','127.0.0.1']).toContain(new URL(process.env.PLAYWRIGHT_BASE_URL!).hostname);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/login?redirectedFrom=/assessment');
  await page.getByLabel('Email').fill(email!);
  await page.getByLabel('Contraseña').fill('UmbraE2E-Test-1234!');
  await page.getByRole('button', { name: /^Entrar$/ }).click();
  await page.waitForURL('**/assessment');
  await expect(page.getByRole('checkbox')).toBeVisible({ timeout: 30_000 });
  const beforeResponse = await page.request.get('/api/account/export');
  expect(beforeResponse.ok(), await beforeResponse.text()).toBe(true);
  const before = await beforeResponse.json();
  const profile = before.psychological_profiles[0];
  expect(profile.user_id).toBe(before.user.id);
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Empezar las 30 preguntas' }).click();
  for (let block=0; block<5; block++) {
    for (let item=0; item<6; item++) await page.locator('fieldset').nth(item).getByRole('radio', { name: 'Neutral, sin opinión' }).check();
    if (block<4) await page.getByRole('button', { name: 'Siguientes 6' }).click();
  }
  const saving = page.waitForResponse(response => new URL(response.url()).pathname === '/api/self-report');
  await page.getByRole('button', { name: 'Guardar y ver mi resultado' }).click();
  const saved = await saving;
  expect(saved.ok(), await saved.text()).toBe(true);
  await expect(page.getByText('Tus respuestas quedaron guardadas.')).toBeVisible();
  const after = await (await page.request.get('/api/account/export')).json();
  const updated = after.psychological_profiles.find((row: {id: string}) => row.id === profile.id);
  expect(updated.analysis_raw.ml).toEqual(profile.analysis_raw.ml);
  expect(updated.analysis_raw.ml.inputSource).toBe('user_open_answers');
  expect(updated.analysis_raw.selfReport.answers).toEqual(Array(30).fill(3));
  expect(updated.analysis_raw.selfReport.researchUse).toBe(false);
  expect(after.profile.research_opt_in).toBe(false);
  const narrative = page.waitForResponse(response => new URL(response.url()).pathname === '/api/narrative', { timeout: 120_000 });
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.waitForURL('**/dashboard');
  const reading = await narrative;
  expect(reading.ok()).toBe(true);
  const events = await reading.text();
  expect(events).toContain('"type":"done"');
  expect(events).not.toContain('"type":"error"');
  await page.reload();
  await expect(page.getByLabel(/: 3.00 sobre 5/)).toHaveCount(5);
  expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
  await page.screenshot({ path: '.impeccable/review/self-report/real-dashboard.png', fullPage: true });
  await page.getByRole('tab', { name: 'Datos del modelo' }).click();
  await expect(page.getByText('evidencia insuficiente — sin cifra', { exact: true })).toHaveCount(5);
  await page.goto('/plan');
  const generating = page.waitForResponse(response => new URL(response.url()).pathname === '/api/plan', { timeout: 120_000 });
  await page.getByRole('button', { name: 'Generar mi plan' }).click();
  const plan = await generating;
  expect(plan.ok(), await plan.text()).toBe(true);
  await expect(page.getByRole('main').getByRole('region')).toHaveCount(3);
  await page.goto('/export');
  await expect(page.locator('.pdf-root')).toContainText('Tu autoinforme BFI-2-S en español');
  await expect(page.locator('.pdf-root').getByText('3,00 / 5', { exact: true })).toHaveCount(5);
  const downloading = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar PDF' }).click();
  const download = await downloading;
  await download.saveAs('.impeccable/review/self-report/real-report.pdf');
  expect(await download.failure()).toBeNull();
  await info.attach('integration', { body: JSON.stringify({ email, mlSource: updated.analysis_raw.ml.inputSource, selfReportIndependent: true, researchOptIn: false }), contentType: 'application/json' });
});
